#!/usr/bin/env bash
#
# Pull the Lucide glyphs the shell uses into shell/assets/Icons.js.
#
#     tools/vendor-icons.sh              re-fetch everything in the list
#     tools/vendor-icons.sh bell power   add names to the list, then fetch
#     tools/vendor-icons.sh --check      fail if a listed icon is missing
#
# Lucide is ISC-licensed. The shell uses a few dozen of its glyphs, so the
# subset is vendored as path data in one JS file; Glyph.qml builds an SVG
# data URL from it with the colour baked in, which needs no shader effect.

set -uo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LIST="$REPO/shell/assets/icons.txt"
OUT="$REPO/shell/assets/Icons.js"
BASE="https://raw.githubusercontent.com/lucide-icons/lucide/main/icons"

check_only=0
add=()
for a in "$@"; do
    case "$a" in
        --check) check_only=1 ;;
        -h|--help) sed -n '3,13p' "${BASH_SOURCE[0]}" | sed 's/^# \?//'; exit 0 ;;
        -*) echo "unknown option: $a" >&2; exit 2 ;;
        *) add+=("$a") ;;
    esac
done

mkdir -p "$(dirname "$LIST")"
[[ -f "$LIST" ]] || : > "$LIST"
if ((${#add[@]})); then
    printf '%s\n' "${add[@]}" >> "$LIST"
    sort -u -o "$LIST" "$LIST"
fi
mapfile -t names < <(grep -vE '^\s*(#|$)' "$LIST")

if ((check_only)); then
    rc=0
    for n in "${names[@]}"; do
        grep -q "^  \"$n\":" "$OUT" 2>/dev/null || { echo "missing: $n"; rc=1; }
    done
    exit $rc
fi

tmp=$(mktemp); trap 'rm -f "$tmp"' EXIT
{
    echo ".pragma library"
    echo "// Lucide glyph bodies, viewBox 0 0 24 24. Generated by tools/vendor-icons.sh; do not edit."
    echo "const paths = {"
} > "$tmp"
failed=0
for n in "${names[@]}"; do
    svg=$(curl -fsSL "$BASE/$n.svg") || { echo "fetch failed: $n" >&2; failed=1; continue; }
    # Keep only the element bodies between the <svg> tags, on one line.
    body=$(printf '%s' "$svg" | sed -n '/<svg/,/<\/svg>/p' | sed '1,/^>$/d; /<\/svg>/d' | tr -d '\n' | sed 's/  */ /g; s/^ //; s/ $//')
    printf '  "%s": %s,\n' "$n" "$(printf '%s' "$body" | python3 -c 'import json,sys; print(json.dumps(sys.stdin.read()))')" >> "$tmp"
    echo "  $n"
done
echo "};" >> "$tmp"
cat >> "$tmp" <<'JS'

// An SVG data URL for `name` at `size` px in `color`, stroke width `weight`.
function url(name, color, size, weight) {
    const body = paths[name];
    if (body === undefined) return "";
    const svg = '<svg xmlns="http://www.w3.org/2000/svg" width="' + size + '" height="' + size
        + '" viewBox="0 0 24 24" fill="none" stroke="' + color + '" stroke-width="' + weight
        + '" stroke-linecap="round" stroke-linejoin="round">' + body + '</svg>';
    return "data:image/svg+xml;utf8," + encodeURIComponent(svg);
}
JS
mv "$tmp" "$OUT"
((failed)) && exit 1
echo "wrote $OUT (${#names[@]} icons)"
